import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  boolean,
  integer,
  decimal,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { tenants } from "./tenants";

// ==========================================
// Chart of Accounts Management
// ==========================================
export const glfrChartOfAccounts = pgTable(
  "glfr_chart_of_accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    accountRef: varchar("account_ref", { length: 50 }).notNull(),
    accountType: varchar("account_type", { length: 30 }).notNull(), // asset, liability, equity, revenue, expense
    accountCode: varchar("account_code", { length: 50 }).notNull(),
    accountName: varchar("account_name", { length: 255 }).notNull(),
    parentAccountId: varchar("parent_account_id", { length: 100 }),
    accountLevel: integer("account_level"),
    currency: varchar("currency", { length: 3 }).default("QAR"),
    normalBalance: varchar("normal_balance", { length: 10 }), // debit, credit
    isControlAccount: boolean("is_control_account"),
    isReconcilable: boolean("is_reconcilable"),
    isBankAccount: boolean("is_bank_account"),
    segment: varchar("segment", { length: 100 }),
    costCenter: varchar("cost_center", { length: 100 }),
    department: varchar("department", { length: 255 }),
    taxCode: varchar("tax_code", { length: 50 }),
    openingBalance: decimal("opening_balance", { precision: 18, scale: 2 }),
    currentBalance: decimal("current_balance", { precision: 18, scale: 2 }),
    description: text("description"),
    status: varchar("status", { length: 20 }).notNull().default("active"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_coa_tenant_idx").on(t.tenantId),
    index("glfr_coa_ref_idx").on(t.accountRef),
    index("glfr_coa_code_idx").on(t.accountCode),
    index("glfr_coa_status_idx").on(t.status),
    index("glfr_coa_type_idx").on(t.accountType),
  ]
);

// ==========================================
// Journal Entry & Posting Management
// ==========================================
export const glfrJournalEntries = pgTable(
  "glfr_journal_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    entryRef: varchar("entry_ref", { length: 50 }).notNull(),
    entryType: varchar("entry_type", { length: 30 }).notNull(), // standard, adjusting, closing, reversing, recurring, accrual
    entryDate: timestamp("entry_date", { withTimezone: true }),
    postingDate: timestamp("posting_date", { withTimezone: true }),
    periodId: varchar("period_id", { length: 100 }),
    description: text("description"),
    currency: varchar("currency", { length: 3 }).default("QAR"),
    totalDebit: decimal("total_debit", { precision: 18, scale: 2 }),
    totalCredit: decimal("total_credit", { precision: 18, scale: 2 }),
    lineItems: jsonb("line_items"),
    sourceModule: varchar("source_module", { length: 100 }),
    sourceDocumentRef: varchar("source_document_ref", { length: 100 }),
    reversalEntryId: varchar("reversal_entry_id", { length: 100 }),
    isAutoGenerated: boolean("is_auto_generated"),
    preparedBy: varchar("prepared_by", { length: 255 }),
    reviewedBy: varchar("reviewed_by", { length: 255 }),
    approvedBy: varchar("approved_by", { length: 255 }),
    postedBy: varchar("posted_by", { length: 255 }),
    postedAt: timestamp("posted_at", { withTimezone: true }),
    status: varchar("status", { length: 20 }).notNull().default("draft"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_je_tenant_idx").on(t.tenantId),
    index("glfr_je_ref_idx").on(t.entryRef),
    index("glfr_je_status_idx").on(t.status),
    index("glfr_je_date_idx").on(t.entryDate),
  ]
);

// ==========================================
// Period Close Procedures Automation
// ==========================================
export const glfrPeriodClosures = pgTable(
  "glfr_period_closures",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    closureRef: varchar("closure_ref", { length: 50 }).notNull(),
    closureType: varchar("closure_type", { length: 30 }).notNull(), // monthly, quarterly, annual, interim, soft_close
    periodName: varchar("period_name", { length: 100 }),
    periodStart: timestamp("period_start", { withTimezone: true }),
    periodEnd: timestamp("period_end", { withTimezone: true }),
    fiscalYear: integer("fiscal_year"),
    fiscalMonth: integer("fiscal_month"),
    checklistItems: jsonb("checklist_items"),
    completedSteps: integer("completed_steps"),
    totalSteps: integer("total_steps"),
    accrualEntries: jsonb("accrual_entries"),
    reclassifications: jsonb("reclassifications"),
    closedBy: varchar("closed_by", { length: 255 }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    reopenedBy: varchar("reopened_by", { length: 255 }),
    reopenedAt: timestamp("reopened_at", { withTimezone: true }),
    status: varchar("status", { length: 20 }).notNull().default("open"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_pc_tenant_idx").on(t.tenantId),
    index("glfr_pc_ref_idx").on(t.closureRef),
    index("glfr_pc_status_idx").on(t.status),
    index("glfr_pc_year_idx").on(t.fiscalYear),
  ]
);

// ==========================================
// IFRS Financial Statements Generation
// ==========================================
export const glfrFinancialStatements = pgTable(
  "glfr_financial_statements",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    statementRef: varchar("statement_ref", { length: 50 }).notNull(),
    statementType: varchar("statement_type", { length: 30 }).notNull(), // balance_sheet, income_statement, cash_flow, equity_changes, comprehensive_income
    reportingStandard: varchar("reporting_standard", { length: 30 }), // ifrs, gaap, local
    periodStart: timestamp("period_start", { withTimezone: true }),
    periodEnd: timestamp("period_end", { withTimezone: true }),
    fiscalYear: integer("fiscal_year"),
    currency: varchar("currency", { length: 3 }).default("QAR"),
    entityId: varchar("entity_id", { length: 100 }),
    lineItems: jsonb("line_items"),
    comparativePeriod: jsonb("comparative_period"),
    totalAssets: decimal("total_assets", { precision: 18, scale: 2 }),
    totalLiabilities: decimal("total_liabilities", { precision: 18, scale: 2 }),
    totalEquity: decimal("total_equity", { precision: 18, scale: 2 }),
    netIncome: decimal("net_income", { precision: 18, scale: 2 }),
    generatedBy: varchar("generated_by", { length: 255 }),
    generatedAt: timestamp("generated_at", { withTimezone: true }),
    approvedBy: varchar("approved_by", { length: 255 }),
    status: varchar("status", { length: 20 }).notNull().default("draft"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_fs_tenant_idx").on(t.tenantId),
    index("glfr_fs_ref_idx").on(t.statementRef),
    index("glfr_fs_status_idx").on(t.status),
    index("glfr_fs_type_idx").on(t.statementType),
  ]
);

// ==========================================
// Segment Reporting by Entity & Trade Lane
// ==========================================
export const glfrSegmentReports = pgTable(
  "glfr_segment_reports",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    reportRef: varchar("report_ref", { length: 50 }).notNull(),
    reportType: varchar("report_type", { length: 30 }).notNull(), // entity, trade_lane, geography, business_unit, product_line
    segmentName: varchar("segment_name", { length: 255 }),
    periodStart: timestamp("period_start", { withTimezone: true }),
    periodEnd: timestamp("period_end", { withTimezone: true }),
    fiscalYear: integer("fiscal_year"),
    currency: varchar("currency", { length: 3 }).default("QAR"),
    revenue: decimal("revenue", { precision: 18, scale: 2 }),
    costOfRevenue: decimal("cost_of_revenue", { precision: 18, scale: 2 }),
    grossProfit: decimal("gross_profit", { precision: 18, scale: 2 }),
    operatingExpenses: decimal("operating_expenses", { precision: 18, scale: 2 }),
    operatingIncome: decimal("operating_income", { precision: 18, scale: 2 }),
    segmentAssets: decimal("segment_assets", { precision: 18, scale: 2 }),
    segmentLiabilities: decimal("segment_liabilities", { precision: 18, scale: 2 }),
    interSegmentRevenue: decimal("inter_segment_revenue", { precision: 18, scale: 2 }),
    breakdownItems: jsonb("breakdown_items"),
    status: varchar("status", { length: 20 }).notNull().default("draft"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_sr_tenant_idx").on(t.tenantId),
    index("glfr_sr_ref_idx").on(t.reportRef),
    index("glfr_sr_status_idx").on(t.status),
    index("glfr_sr_type_idx").on(t.reportType),
  ]
);

// ==========================================
// Consolidated Financial Statements
// ==========================================
export const glfrConsolidatedStatements = pgTable(
  "glfr_consolidated_statements",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    consolidationRef: varchar("consolidation_ref", { length: 50 }).notNull(),
    consolidationType: varchar("consolidation_type", { length: 30 }).notNull(), // full, proportional, equity_method, elimination
    periodStart: timestamp("period_start", { withTimezone: true }),
    periodEnd: timestamp("period_end", { withTimezone: true }),
    fiscalYear: integer("fiscal_year"),
    currency: varchar("currency", { length: 3 }).default("QAR"),
    parentEntity: varchar("parent_entity", { length: 255 }),
    subsidiaries: jsonb("subsidiaries"),
    eliminationEntries: jsonb("elimination_entries"),
    translationAdjustments: jsonb("translation_adjustments"),
    minorityInterest: decimal("minority_interest", { precision: 18, scale: 2 }),
    consolidatedRevenue: decimal("consolidated_revenue", { precision: 18, scale: 2 }),
    consolidatedNetIncome: decimal("consolidated_net_income", { precision: 18, scale: 2 }),
    consolidatedAssets: decimal("consolidated_assets", { precision: 18, scale: 2 }),
    consolidatedLiabilities: decimal("consolidated_liabilities", { precision: 18, scale: 2 }),
    consolidatedEquity: decimal("consolidated_equity", { precision: 18, scale: 2 }),
    preparedBy: varchar("prepared_by", { length: 255 }),
    approvedBy: varchar("approved_by", { length: 255 }),
    status: varchar("status", { length: 20 }).notNull().default("draft"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_cs_tenant_idx").on(t.tenantId),
    index("glfr_cs_ref_idx").on(t.consolidationRef),
    index("glfr_cs_status_idx").on(t.status),
    index("glfr_cs_type_idx").on(t.consolidationType),
  ]
);

// ==========================================
// Budget Planning & Management
// ==========================================
export const glfrBudgets = pgTable(
  "glfr_budgets",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    budgetRef: varchar("budget_ref", { length: 50 }).notNull(),
    budgetType: varchar("budget_type", { length: 30 }).notNull(), // annual, quarterly, rolling, zero_based, incremental
    budgetName: varchar("budget_name", { length: 255 }),
    fiscalYear: integer("fiscal_year"),
    periodStart: timestamp("period_start", { withTimezone: true }),
    periodEnd: timestamp("period_end", { withTimezone: true }),
    currency: varchar("currency", { length: 3 }).default("QAR"),
    department: varchar("department", { length: 255 }),
    costCenter: varchar("cost_center", { length: 100 }),
    totalBudgeted: decimal("total_budgeted", { precision: 18, scale: 2 }),
    totalActual: decimal("total_actual", { precision: 18, scale: 2 }),
    totalVariance: decimal("total_variance", { precision: 18, scale: 2 }),
    variancePercentage: decimal("variance_percentage", { precision: 8, scale: 2 }),
    lineItems: jsonb("line_items"),
    revisionHistory: jsonb("revision_history"),
    currentRevision: integer("current_revision"),
    preparedBy: varchar("prepared_by", { length: 255 }),
    approvedBy: varchar("approved_by", { length: 255 }),
    status: varchar("status", { length: 20 }).notNull().default("draft"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_bgt_tenant_idx").on(t.tenantId),
    index("glfr_bgt_ref_idx").on(t.budgetRef),
    index("glfr_bgt_status_idx").on(t.status),
    index("glfr_bgt_year_idx").on(t.fiscalYear),
  ]
);

// ==========================================
// Variance Analysis & Commentary
// ==========================================
export const glfrVarianceAnalyses = pgTable(
  "glfr_variance_analyses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    analysisRef: varchar("analysis_ref", { length: 50 }).notNull(),
    analysisType: varchar("analysis_type", { length: 30 }).notNull(), // budget_vs_actual, period_over_period, forecast_vs_actual, plan_vs_actual
    periodStart: timestamp("period_start", { withTimezone: true }),
    periodEnd: timestamp("period_end", { withTimezone: true }),
    fiscalYear: integer("fiscal_year"),
    currency: varchar("currency", { length: 3 }).default("QAR"),
    budgetAmount: decimal("budget_amount", { precision: 18, scale: 2 }),
    actualAmount: decimal("actual_amount", { precision: 18, scale: 2 }),
    varianceAmount: decimal("variance_amount", { precision: 18, scale: 2 }),
    variancePercentage: decimal("variance_percentage", { precision: 8, scale: 2 }),
    favorableUnfavorable: varchar("favorable_unfavorable", { length: 20 }), // favorable, unfavorable
    department: varchar("department", { length: 255 }),
    costCenter: varchar("cost_center", { length: 100 }),
    accountCode: varchar("account_code", { length: 50 }),
    lineItems: jsonb("line_items"),
    commentary: text("commentary"),
    actionItems: jsonb("action_items"),
    preparedBy: varchar("prepared_by", { length: 255 }),
    reviewedBy: varchar("reviewed_by", { length: 255 }),
    status: varchar("status", { length: 20 }).notNull().default("draft"),
    notes: text("notes"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    index("glfr_va_tenant_idx").on(t.tenantId),
    index("glfr_va_ref_idx").on(t.analysisRef),
    index("glfr_va_status_idx").on(t.status),
    index("glfr_va_type_idx").on(t.analysisType),
  ]
);
