-- Seed CS ERP issues from 2026-03-20 full audit

-- CRITICAL (7)
INSERT INTO cs_erp_issue_tracker (issue_id, title, severity, category, status, description, root_cause_analysis, root_cause_pattern, affected_files, session_id, sequence_num) VALUES
('CSERP-001', '55 form components missing CSRF token header', 'critical', 'security', 'identified', '55 module form components send POST/PATCH/PUT fetch() with Content-Type but no x-csrf-token header. Every create/update fails with 403.', 'All form components generated from template missing CSRF header. 16 files have correct pattern but 55 do not.', 'pattern-not-inherited-by-new-code', '["src/components/*/form.tsx — 55 files"]', 'cs-erp-audit-2026-03-20', 1),
('CSERP-002', '2 files use wrong getCsrfToken — reads csrf_token cookie instead of cs_csrf', 'critical', 'security', 'identified', 'e2e-flows/definition and processes/instances define local getCsrfToken() reading wrong cookie (csrf_token vs cs_csrf), falling back to hardcoded "csrf-placeholder".', 'Copy-pasted from unknown source instead of importing @/lib/client/csrf.', 'copy-paste-wrong-implementation', '["src/app/(dashboard)/e2e-flows/definition/[flowId]/page.tsx", "src/app/(dashboard)/processes/instances/[id]/page.tsx"]', 'cs-erp-audit-2026-03-20', 2),
('CSERP-003', 'PATCH route allows bypassing human approval gates', 'critical', 'pipeline', 'identified', 'advanceFlowStep() only blocks completed/failed/missing. A flow in paused_at_gate can be advanced via PATCH, bypassing gate resolution.', 'Execute route has proper status guards, PATCH route does not.', 'missing-status-guard', '["src/lib/process-engine/e2e-flow-service.ts"]', 'cs-erp-audit-2026-03-20', 3),
('CSERP-004', 'FOR UPDATE without transaction — no concurrency protection', 'critical', 'pipeline', 'identified', 'executeCurrentStep() uses .for("update") but NOT inside db.transaction(). Lock releases immediately. Two simultaneous /execute calls can execute same step twice.', 'FOR UPDATE added as safeguard but not wrapped in transaction.', 'lock-without-transaction', '["src/lib/process-engine/step-executor.ts"]', 'cs-erp-audit-2026-03-20', 4),
('CSERP-005', 'AI Assist buttons broken — missing stepNumber in request body', 'critical', 'integration', 'identified', 'handleAiAssist() sends {action} but omits stepNumber. aiAssistSchema requires stepNumber. All 3 buttons always fail validation.', 'UI sends only {action}, API requires {action, stepNumber}. Never E2E tested.', 'frontend-api-contract-mismatch', '["src/app/(dashboard)/e2e-flows/[id]/page.tsx"]', 'cs-erp-audit-2026-03-20', 5),
('CSERP-006', 'set_config session-scope with PgBouncer — cross-tenant data leakage', 'critical', 'security', 'identified', 'setTenantRLS() uses set_config(app.tenant_id, tenantId, false) = session-scope. With PgBouncer transaction pooling, stale tenant_id from User A can leak to User B on same connection.', 'setTenantRLS written before PgBouncer. withTenant() has correct true param but setTenantRLS still uses false.', 'pgbouncer-session-scope-leak', '["src/lib/db.ts"]', 'cs-erp-audit-2026-03-20', 6),
('CSERP-007', 'INTERNAL_API_KEY not set — crons never run', 'critical', 'deployment', 'identified', 'Session cleanup + overdue invoice cron endpoints check INTERNAL_API_KEY but it is not in .env.local. Sessions accumulate indefinitely.', 'Endpoints created with key auth but key never configured in environment.', 'env-var-not-configured', '["src/app/api/internal/cron/session-cleanup/route.ts", "src/app/api/internal/cron/overdue-invoices/route.ts"]', 'cs-erp-audit-2026-03-20', 7);

-- HIGH (7)
INSERT INTO cs_erp_issue_tracker (issue_id, title, severity, category, status, description, root_cause_analysis, root_cause_pattern, affected_files, session_id, sequence_num) VALUES
('CSERP-008', '62 HTML form DELETE buttons cannot send CSRF header', 'high', 'security', 'identified', '62 detail pages use <form method=POST> for delete. HTML forms cannot send custom headers. Need conversion to fetch() or hidden CSRF field.', 'Delete buttons implemented as HTML form POSTs. CSRF protection requires custom header.', 'html-form-cannot-send-headers', '["src/app/(dashboard)/*/[id]/page.tsx — 62 files"]', 'cs-erp-audit-2026-03-20', 8),
('CSERP-009', 'Register endpoint does not set CSRF cookie', 'high', 'auth', 'identified', 'After registration, setAuthCookies called but setCsrfCookie() never called. New users get 403 on every mutation until refresh/re-login.', 'Register route modeled after login but setCsrfCookie line was missed.', 'incomplete-feature-shipped', '["src/app/api/auth/register/route.ts"]', 'cs-erp-audit-2026-03-20', 9),
('CSERP-010', 'No JWT revocation — tokens valid 15min after logout', 'high', 'auth', 'identified', 'Logout revokes session but not the access JWT. Stateless JWT with 15-min expiry remains valid after logout/password reset.', 'Standard stateless JWT limitation. No blacklist implemented.', 'stateless-jwt-no-blacklist', '["src/lib/jwt.ts", "src/app/api/auth/logout/route.ts"]', 'cs-erp-audit-2026-03-20', 10),
('CSERP-011', 'Webhook routes accept attacker-controlled x-tenant-id', 'high', 'security', 'identified', 'GPS ingest and container event webhooks use x-tenant-id header for tenant scoping. Shared HMAC secret = any caller can write to any tenant.', 'Single shared webhook secret across all tenants.', 'shared-secret-cross-tenant', '["src/app/api/v1/tracking/gps-ingest/route.ts", "src/app/api/v1/tracking/container-event/route.ts"]', 'cs-erp-audit-2026-03-20', 11),
('CSERP-012', 'x-forwarded-for IP spoofing bypasses rate limits', 'high', 'security', 'identified', 'Client IP from x-forwarded-for can be spoofed. IP-keyed rate limits (register, forgot-password) can be bypassed.', 'Caddy not configured to strip client-provided x-forwarded-for.', 'ip-spoofing-in-rate-limit', '["src/lib/request.ts"]', 'cs-erp-audit-2026-03-20', 12),
('CSERP-013', 'Dashboard sidebar links to / instead of /dashboard', 'high', 'navigation', 'identified', 'Sidebar Dashboard href="/". No page.tsx at /. Every click: / → redirect /dashboard → render. Wasted hop.', 'Sidebar assumes root renders dashboard. Instead root redirects.', 'wrong-href-in-navigation', '["src/lib/navigation/categories.ts"]', 'cs-erp-audit-2026-03-20', 13),
('CSERP-014', 'Sidebar active state never highlights inside module pages', 'high', 'ux', 'identified', 'NavItem checks pathname.startsWith(hubUrl) but module URLs dont match hub URLs. No highlight inside any module.', 'Active state uses hub URLs (/bookings-hub) but modules use /customer-portal/bookings.', 'active-state-logic-mismatch', '["src/components/layout/nav-item.tsx"]', 'cs-erp-audit-2026-03-20', 14);

-- MEDIUM (8)
INSERT INTO cs_erp_issue_tracker (issue_id, title, severity, category, status, description, root_cause_pattern, affected_files, session_id, sequence_num) VALUES
('CSERP-015', 'startedAt never set on flow creation — analytics always 0', 'medium', 'schema', 'identified', 'createFlowInstance() never sets startedAt. avgDurationMinutes = completedAt - startedAt = NULL.', 'incomplete-feature-shipped', '["src/lib/process-engine/e2e-flow-service.ts"]', 'cs-erp-audit-2026-03-20', 15),
('CSERP-016', 'Gate resolution can resurrect cancelled flows', 'medium', 'pipeline', 'identified', 'resolveHumanGate() sets flow to active unconditionally. Cancelled flows get resurrected.', 'missing-status-guard', '["src/lib/process-engine/e2e-flow-service.ts"]', 'cs-erp-audit-2026-03-20', 16),
('CSERP-017', 'Notification links point to nonexistent /processes/gates/ route', 'medium', 'navigation', 'identified', 'human-gate-manager actionUrl = /processes/gates/{gateId}. Actual page is /e2e-flows/gates.', 'wrong-route-in-notification', '["src/lib/process-engine/human-gate-manager.ts"]', 'cs-erp-audit-2026-03-20', 17),
('CSERP-018', 'Event log writes escape transaction boundary', 'medium', 'schema', 'identified', 'logFlowEvent() inside advanceFlowStep() transaction uses db.insert() not tx.insert(). Orphaned events on rollback.', 'db-write-outside-transaction', '["src/lib/process-engine/e2e-flow-service.ts"]', 'cs-erp-audit-2026-03-20', 18),
('CSERP-019', 'No rate limiting on expensive /execute endpoint', 'medium', 'security', 'identified', 'Execute triggers AI calls (90s timeout, 5 tool iterations) with no rate limit. CLAUDE.md requires it.', 'missing-rate-limiting', '["src/app/api/v1/process-engine/e2e-flows/[id]/execute/route.ts"]', 'cs-erp-audit-2026-03-20', 19),
('CSERP-020', 'Auto-approve fire-and-forget can leave flow stuck', 'medium', 'pipeline', 'identified', 'attemptAutoApprove() calls resumeAfterGate() with .catch(). If it throws, flow stuck at active.', 'fire-and-forget-without-error-handling', '["src/lib/process-engine/human-gate-manager.ts"]', 'cs-erp-audit-2026-03-20', 20),
('CSERP-021', 'CategoryHubPage has no dark mode support', 'medium', 'ux', 'identified', 'All 8+ hub pages use hardcoded light-only colors. CLAUDE.md requires dark mode.', 'missing-dark-mode-variants', '["src/components/hub/category-hub-page.tsx"]', 'cs-erp-audit-2026-03-20', 21),
('CSERP-022', '1,475 pages missing loading.tsx (only 31% coverage)', 'medium', 'ux', 'identified', 'Only 677/2,152 pages have loading.tsx. Missing on dashboard, all hubs, admin. CLAUDE.md requires it.', 'missing-loading-states', '["src/app/(dashboard)/"]', 'cs-erp-audit-2026-03-20', 22);
