CREATE TABLE "vpe_carbon_emissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"emission_ref" varchar(100) NOT NULL,
	"emission_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"voyage_id" varchar(100),
	"reporting_period_start" timestamp with time zone,
	"reporting_period_end" timestamp with time zone,
	"total_co2_mt" numeric(14, 3),
	"total_ch4_mt" numeric(14, 6),
	"total_n2o_mt" numeric(14, 6),
	"co2e_total" numeric(14, 3),
	"fuel_consumed_mt" numeric(14, 3),
	"emission_factor" numeric(10, 6),
	"eu_mrv_compliance" boolean,
	"imo_data_collection" boolean,
	"eu_ets_liability" numeric(14, 2),
	"carbon_intensity" numeric(12, 6),
	"reduction_target" numeric(8, 2),
	"reduction_achieved" numeric(8, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vpe_cii_ratings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"rating_ref" varchar(100) NOT NULL,
	"rating_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"imo_number" varchar(20),
	"reporting_year" integer,
	"attained_cii" numeric(12, 6),
	"required_cii" numeric(12, 6),
	"reduction_factor" numeric(8, 4),
	"rating" varchar(1),
	"total_co2_emissions" numeric(14, 3),
	"total_distance_nm" numeric(14, 2),
	"dwt" numeric(12, 2),
	"correction_factors" jsonb,
	"compliance_status" varchar(50),
	"corrective_action_plan" text,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vpe_eexi_compliances" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"compliance_ref" varchar(100) NOT NULL,
	"compliance_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"imo_number" varchar(20),
	"attained_eexi" numeric(12, 6),
	"required_eexi" numeric(12, 6),
	"reference_line" numeric(12, 6),
	"reduction_percentage" numeric(8, 2),
	"engine_power_limitation" boolean,
	"epl_percentage" numeric(8, 2),
	"shaft_power_limitation" boolean,
	"energy_saving_devices" jsonb,
	"survey_date" timestamp with time zone,
	"certificate_number" varchar(100),
	"certificate_expiry" timestamp with time zone,
	"flag_state" varchar(100),
	"classification_society" varchar(255),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vpe_fuel_benchmarks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"benchmark_ref" varchar(100) NOT NULL,
	"benchmark_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"vessel_class" varchar(100),
	"period_start" timestamp with time zone,
	"period_end" timestamp with time zone,
	"avg_daily_consumption" numeric(12, 3),
	"benchmark_consumption" numeric(12, 3),
	"efficiency_ratio" numeric(8, 4),
	"fuel_cost_per_nm" numeric(10, 4),
	"co2_per_nm" numeric(10, 6),
	"fleet_ranking" integer,
	"total_vessels_in_class" integer,
	"percentile" numeric(5, 2),
	"trend_direction" varchar(20),
	"recommendations" jsonb,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vpe_noon_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"report_ref" varchar(100) NOT NULL,
	"report_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"voyage_id" varchar(100),
	"report_datetime" timestamp with time zone,
	"latitude" numeric(10, 6),
	"longitude" numeric(10, 6),
	"course_heading" numeric(6, 2),
	"distance_since_last_report" numeric(10, 2),
	"distance_to_go" numeric(10, 2),
	"avg_speed" numeric(8, 2),
	"wind_direction" varchar(10),
	"wind_force" integer,
	"sea_state" varchar(50),
	"swell_height" numeric(6, 2),
	"rob_fo" numeric(12, 3),
	"rob_do" numeric(12, 3),
	"rob_lo" numeric(12, 3),
	"me_consumption" numeric(10, 3),
	"ae_consumption" numeric(10, 3),
	"boiler_consumption" numeric(10, 3),
	"eta" timestamp with time zone,
	"master_remarks" text,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vpe_speed_consumptions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"consumption_ref" varchar(100) NOT NULL,
	"consumption_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"voyage_id" varchar(100),
	"report_date" timestamp with time zone,
	"speed_ordered" numeric(10, 2),
	"speed_actual" numeric(10, 2),
	"speed_over_ground" numeric(10, 2),
	"fuel_consumed_mt" numeric(12, 3),
	"fuel_type" varchar(50),
	"daily_consumption" numeric(12, 3),
	"distance_traveled" numeric(12, 2),
	"slip_percentage" numeric(8, 2),
	"wind_force" integer,
	"sea_state" varchar(50),
	"current_factor" numeric(8, 3),
	"performance_index" numeric(8, 4),
	"weather_impact" varchar(50),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vpe_voyage_performances" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"performance_ref" varchar(100) NOT NULL,
	"performance_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"voyage_id" varchar(100),
	"charter_party_id" varchar(100),
	"cp_speed" numeric(8, 2),
	"actual_speed" numeric(8, 2),
	"speed_variance" numeric(8, 2),
	"cp_consumption" numeric(12, 3),
	"actual_consumption" numeric(12, 3),
	"consumption_variance" numeric(12, 3),
	"good_weather_days" numeric(8, 2),
	"bad_weather_days" numeric(8, 2),
	"claim_amount" numeric(14, 2),
	"claim_currency" varchar(3),
	"claim_direction" varchar(20),
	"analysis_report" jsonb,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vpe_weather_routings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"routing_ref" varchar(100) NOT NULL,
	"routing_type" varchar(50) NOT NULL,
	"vessel_id" varchar(100),
	"vessel_name" varchar(255),
	"voyage_id" varchar(100),
	"departure_port" varchar(255),
	"arrival_port" varchar(255),
	"departure_date" timestamp with time zone,
	"arrival_date" timestamp with time zone,
	"optimized_eta" timestamp with time zone,
	"route_waypoints" jsonb,
	"total_distance_nm" numeric(12, 2),
	"estimated_fuel_mt" numeric(12, 3),
	"fuel_saving_mt" numeric(12, 3),
	"time_saving_hours" numeric(10, 2),
	"weather_forecast" jsonb,
	"risk_assessment" varchar(50),
	"confidence_score" numeric(5, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "vpe_carbon_emissions" ADD CONSTRAINT "vpe_carbon_emissions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vpe_cii_ratings" ADD CONSTRAINT "vpe_cii_ratings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vpe_eexi_compliances" ADD CONSTRAINT "vpe_eexi_compliances_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vpe_fuel_benchmarks" ADD CONSTRAINT "vpe_fuel_benchmarks_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vpe_noon_reports" ADD CONSTRAINT "vpe_noon_reports_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vpe_speed_consumptions" ADD CONSTRAINT "vpe_speed_consumptions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vpe_voyage_performances" ADD CONSTRAINT "vpe_voyage_performances_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vpe_weather_routings" ADD CONSTRAINT "vpe_weather_routings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;