CREATE TABLE "ccm_claim_predictions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"prediction_ref" varchar(100) NOT NULL,
	"prediction_type" varchar(50) NOT NULL,
	"claim_id" varchar(100),
	"vessel_name" varchar(255),
	"model_version" varchar(50),
	"input_features" jsonb,
	"success_probability" numeric(5, 4),
	"predicted_settlement" numeric(14, 2),
	"confidence_interval" varchar(50),
	"estimated_duration_days" integer,
	"risk_score" numeric(5, 2),
	"recommended_action" text,
	"similar_cases_count" integer,
	"historical_avg_settlement" numeric(14, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ccm_claim_registrations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"claim_ref" varchar(100) NOT NULL,
	"claim_type" varchar(50) NOT NULL,
	"claimant_name" varchar(255),
	"claimant_email" varchar(255),
	"claimant_phone" varchar(50),
	"vessel_name" varchar(255),
	"voyage_ref" varchar(100),
	"bl_number" varchar(100),
	"container_numbers" text,
	"port_of_loading" varchar(255),
	"port_of_discharge" varchar(255),
	"cargo_description" text,
	"claim_amount_usd" numeric(14, 2),
	"claim_currency" varchar(3),
	"claim_amount_original" numeric(14, 2),
	"date_of_loss" timestamp with time zone,
	"date_notified" timestamp with time zone,
	"triage_priority" varchar(20),
	"assigned_handler" varchar(255),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ccm_claim_settlements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"settlement_ref" varchar(100) NOT NULL,
	"settlement_type" varchar(50) NOT NULL,
	"claim_id" varchar(100),
	"vessel_name" varchar(255),
	"original_claim_amount" numeric(14, 2),
	"offered_amount" numeric(14, 2),
	"settled_amount" numeric(14, 2),
	"settlement_currency" varchar(3),
	"settlement_date" timestamp with time zone,
	"payment_method" varchar(50),
	"payment_reference" varchar(100),
	"payment_date" timestamp with time zone,
	"release_obtained" boolean,
	"release_date" timestamp with time zone,
	"savings_amount" numeric(14, 2),
	"savings_percentage" numeric(5, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ccm_damage_surveys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"survey_ref" varchar(100) NOT NULL,
	"survey_type" varchar(50) NOT NULL,
	"claim_id" varchar(100),
	"vessel_name" varchar(255),
	"surveyor_name" varchar(255),
	"surveyor_company" varchar(255),
	"survey_date" timestamp with time zone,
	"survey_location" varchar(255),
	"damage_type" varchar(100),
	"damage_extent" varchar(50),
	"estimated_damage_usd" numeric(14, 2),
	"container_condition" varchar(100),
	"seal_condition" varchar(100),
	"photos_attached" boolean,
	"report_received" boolean,
	"report_date" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ccm_liability_assessments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"assessment_ref" varchar(100) NOT NULL,
	"assessment_type" varchar(50) NOT NULL,
	"claim_id" varchar(100),
	"vessel_name" varchar(255),
	"applicable_convention" varchar(100),
	"liability_basis" text,
	"limitation_applied" boolean,
	"limit_per_package" numeric(14, 2),
	"limit_per_kg" numeric(14, 4),
	"total_packages" integer,
	"total_weight_kg" numeric(14, 3),
	"calculated_limit" numeric(14, 2),
	"defense_applicable" varchar(100),
	"defense_description" text,
	"recommended_liability" numeric(14, 2),
	"carrier_liability_pct" numeric(5, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ccm_portfolio_analytics" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"analytics_ref" varchar(100) NOT NULL,
	"analytics_type" varchar(50) NOT NULL,
	"reporting_period" varchar(50),
	"total_claims_count" integer,
	"open_claims_count" integer,
	"closed_claims_count" integer,
	"total_incurred_usd" numeric(14, 2),
	"total_paid_usd" numeric(14, 2),
	"total_reserved_usd" numeric(14, 2),
	"total_recovered_usd" numeric(14, 2),
	"loss_ratio" numeric(8, 4),
	"avg_settlement_days" integer,
	"avg_claim_value_usd" numeric(14, 2),
	"top_claim_category" varchar(100),
	"trend_direction" varchar(20),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ccm_subrogation_recoveries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"recovery_ref" varchar(100) NOT NULL,
	"recovery_type" varchar(50) NOT NULL,
	"claim_id" varchar(100),
	"vessel_name" varchar(255),
	"respondent_name" varchar(255),
	"respondent_type" varchar(50),
	"amount_claimed" numeric(14, 2),
	"amount_recovered" numeric(14, 2),
	"recovery_currency" varchar(3),
	"recovery_basis" text,
	"demand_letter_date" timestamp with time zone,
	"response_deadline" timestamp with time zone,
	"recovery_date" timestamp with time zone,
	"legal_action_filed" boolean,
	"recovery_percentage" numeric(5, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ccm_time_bar_trackings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"tracking_ref" varchar(100) NOT NULL,
	"tracking_type" varchar(50) NOT NULL,
	"claim_id" varchar(100),
	"vessel_name" varchar(255),
	"applicable_law" varchar(100),
	"time_bar_period_months" integer,
	"date_of_delivery" timestamp with time zone,
	"time_bar_deadline" timestamp with time zone,
	"days_remaining" integer,
	"extension_granted" boolean,
	"extension_date" timestamp with time zone,
	"alert_sent_30_days" boolean,
	"alert_sent_60_days" boolean,
	"alert_sent_90_days" boolean,
	"protective_action" varchar(100),
	"protective_action_date" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "ccm_claim_predictions" ADD CONSTRAINT "ccm_claim_predictions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ccm_claim_registrations" ADD CONSTRAINT "ccm_claim_registrations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ccm_claim_settlements" ADD CONSTRAINT "ccm_claim_settlements_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ccm_damage_surveys" ADD CONSTRAINT "ccm_damage_surveys_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ccm_liability_assessments" ADD CONSTRAINT "ccm_liability_assessments_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ccm_portfolio_analytics" ADD CONSTRAINT "ccm_portfolio_analytics_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ccm_subrogation_recoveries" ADD CONSTRAINT "ccm_subrogation_recoveries_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ccm_time_bar_trackings" ADD CONSTRAINT "ccm_time_bar_trackings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;