CREATE TABLE "clm_container_redeliveries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"redelivery_ref" varchar(100) NOT NULL,
	"redelivery_type" varchar(50) NOT NULL,
	"agreement_id" varchar(100),
	"container_number" varchar(20),
	"container_type" varchar(50),
	"redelivery_location" varchar(255),
	"depot_name" varchar(255),
	"scheduled_date" timestamp with time zone,
	"actual_date" timestamp with time zone,
	"condition_on_return" varchar(50),
	"cleaning_required" boolean,
	"repair_required" boolean,
	"penalty_applicable" boolean,
	"penalty_amount" numeric(14, 2),
	"dropoff_charges" numeric(14, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clm_fleet_optimizers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"optimizer_ref" varchar(100) NOT NULL,
	"optimizer_type" varchar(50) NOT NULL,
	"model_version" varchar(50),
	"analysis_date" timestamp with time zone,
	"current_fleet_size" integer,
	"recommended_fleet_size" integer,
	"owned_containers" integer,
	"leased_containers" integer,
	"recommended_owned_pct" numeric(5, 2),
	"recommended_leased_pct" numeric(5, 2),
	"projected_savings" numeric(14, 2),
	"utilization_target" numeric(5, 2),
	"confidence_score" numeric(5, 4),
	"input_features" jsonb,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clm_lease_agreements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"agreement_ref" varchar(100) NOT NULL,
	"agreement_type" varchar(50) NOT NULL,
	"lessor_name" varchar(255),
	"lessor_code" varchar(50),
	"container_type" varchar(50),
	"container_size" varchar(20),
	"quantity" integer,
	"daily_rate" numeric(12, 4),
	"rate_currency" varchar(3),
	"minimum_lease_days" integer,
	"commencement_date" timestamp with time zone,
	"expiry_date" timestamp with time zone,
	"pickup_location" varchar(255),
	"dropoff_location" varchar(255),
	"deposit_amount" numeric(14, 2),
	"insurance_required" boolean,
	"auto_renewal" boolean,
	"termination_notice_days" integer,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clm_lease_cost_allocations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"allocation_ref" varchar(100) NOT NULL,
	"allocation_type" varchar(50) NOT NULL,
	"agreement_id" varchar(100),
	"trade_lane" varchar(100),
	"voyage_ref" varchar(100),
	"allocation_period" varchar(50),
	"container_count" integer,
	"total_lease_days" integer,
	"daily_rate" numeric(12, 4),
	"total_cost_allocated" numeric(14, 2),
	"allocation_currency" varchar(3),
	"cost_per_teu" numeric(12, 4),
	"revenue_generated" numeric(14, 2),
	"profit_margin" numeric(8, 4),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clm_lease_vs_buy_analyses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"analysis_ref" varchar(100) NOT NULL,
	"analysis_type" varchar(50) NOT NULL,
	"container_type" varchar(50),
	"container_size" varchar(20),
	"quantity" integer,
	"purchase_price" numeric(14, 2),
	"lease_rate" numeric(12, 4),
	"lease_term" integer,
	"discount_rate" numeric(8, 4),
	"npv_lease" numeric(14, 2),
	"npv_buy" numeric(14, 2),
	"break_even_months" integer,
	"recommendation" varchar(50),
	"savings_amount" numeric(14, 2),
	"analysis_currency" varchar(3),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clm_lessor_reconciliations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"reconciliation_ref" varchar(100) NOT NULL,
	"reconciliation_type" varchar(50) NOT NULL,
	"lessor_name" varchar(255),
	"agreement_id" varchar(100),
	"statement_period" varchar(50),
	"lessor_amount" numeric(14, 2),
	"internal_amount" numeric(14, 2),
	"difference_amount" numeric(14, 2),
	"reconciliation_currency" varchar(3),
	"items_matched" integer,
	"items_unmatched" integer,
	"dispute_count" integer,
	"adjustment_amount" numeric(14, 2),
	"reconciliation_date" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clm_mnr_damage_billings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"billing_ref" varchar(100) NOT NULL,
	"billing_type" varchar(50) NOT NULL,
	"container_number" varchar(20),
	"agreement_id" varchar(100),
	"lessor_name" varchar(255),
	"damage_description" text,
	"damage_location" varchar(100),
	"repair_type" varchar(50),
	"material_cost" numeric(14, 2),
	"labor_cost" numeric(14, 2),
	"total_repair_cost" numeric(14, 2),
	"billing_currency" varchar(3),
	"responsible_party" varchar(100),
	"dispute_raised" boolean,
	"approved_amount" numeric(14, 2),
	"invoice_date" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "clm_onhire_offhires" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"event_ref" varchar(100) NOT NULL,
	"event_type" varchar(50) NOT NULL,
	"agreement_id" varchar(100),
	"container_number" varchar(20),
	"container_type" varchar(50),
	"container_size" varchar(20),
	"event_date" timestamp with time zone,
	"event_location" varchar(255),
	"depot_name" varchar(255),
	"condition_grade" varchar(10),
	"survey_required" boolean,
	"survey_date" timestamp with time zone,
	"daily_rate" numeric(12, 4),
	"days_on_hire" integer,
	"total_cost" numeric(14, 2),
	"interchange_ref" varchar(100),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "clm_container_redeliveries" ADD CONSTRAINT "clm_container_redeliveries_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clm_fleet_optimizers" ADD CONSTRAINT "clm_fleet_optimizers_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clm_lease_agreements" ADD CONSTRAINT "clm_lease_agreements_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clm_lease_cost_allocations" ADD CONSTRAINT "clm_lease_cost_allocations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clm_lease_vs_buy_analyses" ADD CONSTRAINT "clm_lease_vs_buy_analyses_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clm_lessor_reconciliations" ADD CONSTRAINT "clm_lessor_reconciliations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clm_mnr_damage_billings" ADD CONSTRAINT "clm_mnr_damage_billings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clm_onhire_offhires" ADD CONSTRAINT "clm_onhire_offhires_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;