CREATE TABLE "ptt_budget_plannings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"budget_ref" varchar(100) NOT NULL,
	"budget_type" varchar(50) NOT NULL,
	"port_code" varchar(20),
	"port_name" varchar(255),
	"fiscal_year" integer,
	"fiscal_period" varchar(20),
	"budgeted_amount" numeric(14, 2),
	"actual_amount" numeric(14, 2),
	"variance_amount" numeric(14, 2),
	"variance_percentage" numeric(8, 4),
	"budget_currency" varchar(3),
	"cost_category" varchar(50),
	"forecasted_amount" numeric(14, 2),
	"approved_by" varchar(255),
	"approval_date" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ptt_cost_optimizations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"optimization_ref" varchar(100) NOT NULL,
	"optimization_type" varchar(50) NOT NULL,
	"port_code" varchar(20),
	"port_name" varchar(255),
	"current_cost" numeric(14, 2),
	"optimized_cost" numeric(14, 2),
	"projected_savings" numeric(14, 2),
	"savings_percentage" numeric(8, 4),
	"optimization_currency" varchar(3),
	"confidence_score" numeric(5, 2),
	"implementation_difficulty" varchar(20),
	"timeline_weeks" integer,
	"recommendation" text,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ptt_invoice_validations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"validation_ref" varchar(100) NOT NULL,
	"validation_type" varchar(50) NOT NULL,
	"invoice_number" varchar(100),
	"terminal_name" varchar(255),
	"port_code" varchar(20),
	"invoice_date" timestamp with time zone,
	"invoice_amount_claimed" numeric(14, 2),
	"calculated_amount" numeric(14, 2),
	"variance_amount" numeric(14, 2),
	"variance_percentage" numeric(8, 4),
	"invoice_currency" varchar(3),
	"dispute_reason" text,
	"resolution_date" timestamp with time zone,
	"resolved_amount" numeric(14, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ptt_pilotage_towage_charges" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"charge_ref" varchar(100) NOT NULL,
	"charge_type" varchar(50) NOT NULL,
	"port_code" varchar(20),
	"port_name" varchar(255),
	"vessel_name" varchar(255),
	"vessel_grt" numeric(12, 2),
	"vessel_loa" numeric(10, 2),
	"number_of_tugs" integer,
	"tug_hours" numeric(8, 2),
	"pilotage_distance" numeric(10, 2),
	"rate_per_grt" numeric(12, 4),
	"base_charge" numeric(14, 2),
	"calculated_amount" numeric(14, 2),
	"charge_currency" varchar(3),
	"night_surcharge" boolean,
	"weekend_surcharge" boolean,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ptt_port_dues_wharfages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"dues_ref" varchar(100) NOT NULL,
	"dues_type" varchar(50) NOT NULL,
	"port_code" varchar(20),
	"port_name" varchar(255),
	"vessel_name" varchar(255),
	"vessel_grt" numeric(12, 2),
	"vessel_nrt" numeric(12, 2),
	"vessel_loa" numeric(10, 2),
	"rate_per_grt" numeric(12, 4),
	"rate_per_nrt" numeric(12, 4),
	"calculated_amount" numeric(14, 2),
	"dues_currency" varchar(3),
	"berthing_hours" integer,
	"discount_percentage" numeric(8, 4),
	"effective_date" timestamp with time zone,
	"expiry_date" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ptt_storage_demurrage_tariffs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"tariff_ref" varchar(100) NOT NULL,
	"tariff_type" varchar(50) NOT NULL,
	"port_code" varchar(20),
	"port_name" varchar(255),
	"terminal_name" varchar(255),
	"container_size" varchar(20),
	"container_type" varchar(50),
	"free_days" integer,
	"daily_rate_tier1" numeric(12, 2),
	"tier1_days_from" integer,
	"tier1_days_to" integer,
	"daily_rate_tier2" numeric(12, 2),
	"tier2_days_from" integer,
	"tier2_days_to" integer,
	"daily_rate_tier3" numeric(12, 2),
	"tariff_currency" varchar(3),
	"effective_from" timestamp with time zone,
	"effective_to" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ptt_tariff_comparisons" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"comparison_ref" varchar(100) NOT NULL,
	"comparison_type" varchar(50) NOT NULL,
	"base_port_code" varchar(20),
	"base_port_name" varchar(255),
	"compare_port_code" varchar(20),
	"compare_port_name" varchar(255),
	"charge_category" varchar(50),
	"base_port_cost" numeric(14, 2),
	"compare_port_cost" numeric(14, 2),
	"difference_amount" numeric(14, 2),
	"difference_percentage" numeric(8, 4),
	"benchmark_currency" varchar(3),
	"period_from" timestamp with time zone,
	"period_to" timestamp with time zone,
	"recommendation" text,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ptt_terminal_handling_charges" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"charge_ref" varchar(100) NOT NULL,
	"charge_type" varchar(50) NOT NULL,
	"port_code" varchar(20),
	"port_name" varchar(255),
	"terminal_name" varchar(255),
	"terminal_code" varchar(50),
	"container_size" varchar(20),
	"container_type" varchar(50),
	"cargo_category" varchar(50),
	"charge_amount_base" numeric(14, 2),
	"charge_currency" varchar(3),
	"charge_per_unit" varchar(20),
	"effective_from" timestamp with time zone,
	"effective_to" timestamp with time zone,
	"surcharge_percentage" numeric(8, 4),
	"peak_season_multiplier" numeric(6, 4),
	"exemption_applicable" boolean,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "ptt_budget_plannings" ADD CONSTRAINT "ptt_budget_plannings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptt_cost_optimizations" ADD CONSTRAINT "ptt_cost_optimizations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptt_invoice_validations" ADD CONSTRAINT "ptt_invoice_validations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptt_pilotage_towage_charges" ADD CONSTRAINT "ptt_pilotage_towage_charges_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptt_port_dues_wharfages" ADD CONSTRAINT "ptt_port_dues_wharfages_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptt_storage_demurrage_tariffs" ADD CONSTRAINT "ptt_storage_demurrage_tariffs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptt_tariff_comparisons" ADD CONSTRAINT "ptt_tariff_comparisons_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ptt_terminal_handling_charges" ADD CONSTRAINT "ptt_terminal_handling_charges_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;