CREATE TABLE "loc_cargo_cutoffs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"cutoff_ref" varchar(100) NOT NULL,
	"cutoff_type" varchar(50) NOT NULL,
	"port_code" varchar(20),
	"port_name" varchar(255),
	"terminal_name" varchar(255),
	"vessel_name" varchar(255),
	"voyage_number" varchar(50),
	"service_name" varchar(100),
	"cutoff_datetime" timestamp with time zone,
	"extension_granted" boolean,
	"extension_until" timestamp with time zone,
	"extension_reason" text,
	"affected_bookings" integer,
	"notification_sent" boolean,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "loc_cargo_mix_optimizations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"optimization_ref" varchar(100) NOT NULL,
	"optimization_type" varchar(50) NOT NULL,
	"vessel_name" varchar(255),
	"voyage_number" varchar(50),
	"trade_route" varchar(100),
	"current_revenue" numeric(14, 2),
	"optimized_revenue" numeric(14, 2),
	"revenue_uplift" numeric(14, 2),
	"uplift_percentage" numeric(8, 4),
	"revenue_currency" varchar(3),
	"confidence_score" numeric(5, 2),
	"reefer_slots" integer,
	"hazmat_slots" integer,
	"recommendation" text,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "loc_load_factor_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"report_ref" varchar(100) NOT NULL,
	"report_type" varchar(50) NOT NULL,
	"vessel_name" varchar(255),
	"voyage_number" varchar(50),
	"trade_route" varchar(100),
	"total_capacity_teu" numeric(10, 2),
	"loaded_teu" numeric(10, 2),
	"load_factor_percentage" numeric(8, 4),
	"weight_utilization" numeric(8, 4),
	"revenue_per_teu" numeric(14, 2),
	"report_currency" varchar(3),
	"period_from" timestamp with time zone,
	"period_to" timestamp with time zone,
	"empty_repositioning" integer,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "loc_overbooking_rollovers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"rollover_ref" varchar(100) NOT NULL,
	"rollover_type" varchar(50) NOT NULL,
	"vessel_name" varchar(255),
	"voyage_number" varchar(50),
	"port_code" varchar(20),
	"port_name" varchar(255),
	"booking_ref" varchar(100),
	"container_count" integer,
	"teu_count" numeric(10, 2),
	"original_vessel" varchar(255),
	"next_vessel" varchar(255),
	"next_voyage" varchar(50),
	"rollover_reason" text,
	"revenue_impact" numeric(14, 2),
	"impact_currency" varchar(3),
	"customer_notified" boolean,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "loc_revenue_integrity_audits" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"audit_ref" varchar(100) NOT NULL,
	"audit_type" varchar(50) NOT NULL,
	"booking_ref" varchar(100),
	"customer_name" varchar(255),
	"contracted_rate" numeric(14, 2),
	"applied_rate" numeric(14, 2),
	"variance_amount" numeric(14, 2),
	"rate_currency" varchar(3),
	"trade_route" varchar(100),
	"container_type" varchar(50),
	"container_size" varchar(20),
	"leakage_amount" numeric(14, 2),
	"correction_applied" boolean,
	"correction_date" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "loc_rolling_upgrades" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"upgrade_ref" varchar(100) NOT NULL,
	"upgrade_type" varchar(50) NOT NULL,
	"booking_ref" varchar(100),
	"customer_name" varchar(255),
	"original_equipment" varchar(50),
	"upgraded_equipment" varchar(50),
	"original_service" varchar(100),
	"upgraded_service" varchar(100),
	"cost_difference" numeric(14, 2),
	"upgrade_currency" varchar(3),
	"approved_by" varchar(255),
	"approval_date" timestamp with time zone,
	"upgrade_reason" text,
	"revenue_recovered" numeric(14, 2),
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "loc_schedule_deviations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"deviation_ref" varchar(100) NOT NULL,
	"deviation_type" varchar(50) NOT NULL,
	"vessel_name" varchar(255),
	"voyage_number" varchar(50),
	"service_name" varchar(100),
	"original_eta" timestamp with time zone,
	"revised_eta" timestamp with time zone,
	"delay_hours" numeric(8, 2),
	"deviation_reason" text,
	"recovery_plan" text,
	"cost_impact" numeric(14, 2),
	"impact_currency" varchar(3),
	"affected_ports" integer,
	"recovery_achieved" boolean,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "loc_slot_swap_coordinations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"swap_ref" varchar(100) NOT NULL,
	"swap_type" varchar(50) NOT NULL,
	"partner_name" varchar(255),
	"partner_code" varchar(50),
	"vessel_name" varchar(255),
	"voyage_number" varchar(50),
	"trade_route" varchar(100),
	"slots_offered" integer,
	"slots_received" integer,
	"rate_per_slot" numeric(14, 2),
	"total_value" numeric(14, 2),
	"swap_currency" varchar(3),
	"effective_from" timestamp with time zone,
	"effective_to" timestamp with time zone,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"notes" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "loc_cargo_cutoffs" ADD CONSTRAINT "loc_cargo_cutoffs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loc_cargo_mix_optimizations" ADD CONSTRAINT "loc_cargo_mix_optimizations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loc_load_factor_reports" ADD CONSTRAINT "loc_load_factor_reports_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loc_overbooking_rollovers" ADD CONSTRAINT "loc_overbooking_rollovers_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loc_revenue_integrity_audits" ADD CONSTRAINT "loc_revenue_integrity_audits_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loc_rolling_upgrades" ADD CONSTRAINT "loc_rolling_upgrades_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loc_schedule_deviations" ADD CONSTRAINT "loc_schedule_deviations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loc_slot_swap_coordinations" ADD CONSTRAINT "loc_slot_swap_coordinations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;