import { getSession } from "@/lib/auth/session";
import { redirect, notFound } from "next/navigation";
import { hasPermission } from "@/lib/rbac";
import { getJournalEntry } from "@/lib/general-ledger-financial-reporting/service";
import {
  GlfrForm,
  type FieldConfig,
} from "@/components/general-ledger-financial-reporting/glfr-form";
import { getCurrencyOptions } from "@/lib/lookups";

export default async function EditJournalEntryPage({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<React.ReactNode> {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!(await hasPermission(session.id, session.tenantId, "gl:edit")))
    redirect("/general-ledger-financial-reporting/journal-entries");

  const currencyOpts = await getCurrencyOptions();

  const JOURNAL_ENTRY_FIELDS: FieldConfig[] = [
    {
      name: "entryType",
      label: "Entry Type",
      type: "select",
      required: true,
      options: [
        { value: "standard", label: "Standard" },
        { value: "adjusting", label: "Adjusting" },
        { value: "closing", label: "Closing" },
        { value: "reversing", label: "Reversing" },
        { value: "recurring", label: "Recurring" },
        { value: "accrual", label: "Accrual" },
      ],
    },
    { name: "entryDate", label: "Entry Date", type: "datetime-local" },
    { name: "postingDate", label: "Posting Date", type: "datetime-local" },
    { name: "periodId", label: "Period ID", type: "text" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "currency", label: "Currency", type: "select", options: currencyOpts },
    { name: "totalDebit", label: "Total Debit", type: "text" },
    { name: "totalCredit", label: "Total Credit", type: "text" },
    { name: "sourceModule", label: "Source Module", type: "text" },
    { name: "sourceDocumentRef", label: "Source Document Ref", type: "text" },
    { name: "reversalEntryId", label: "Reversal Entry ID", type: "text" },
    { name: "isAutoGenerated", label: "Is Auto Generated", type: "checkbox" },
    { name: "preparedBy", label: "Prepared By", type: "text" },
    { name: "reviewedBy", label: "Reviewed By", type: "text" },
    { name: "approvedBy", label: "Approved By", type: "text" },
    { name: "notes", label: "Notes", type: "textarea" },
  ];
  const { id } = await params;
  const record = await getJournalEntry(id, session.tenantId);
  if (!record) notFound();

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">
          Edit Journal Entry
        </h1>
        <p className="text-sm text-gray-500">
          Update journal entry {record.entryRef}
        </p>
      </div>
      <GlfrForm
        entityType="Journal Entry"
        fields={JOURNAL_ENTRY_FIELDS}
        initialData={{
          entryType: record.entryType ?? "",
          entryDate: record.entryDate
            ? new Date(record.entryDate).toISOString()
            : "",
          postingDate: record.postingDate
            ? new Date(record.postingDate).toISOString()
            : "",
          periodId: record.periodId ?? "",
          description: record.description ?? "",
          currency: record.currency ?? "",
          totalDebit: record.totalDebit ?? "",
          totalCredit: record.totalCredit ?? "",
          sourceModule: record.sourceModule ?? "",
          sourceDocumentRef: record.sourceDocumentRef ?? "",
          reversalEntryId: record.reversalEntryId ?? "",
          isAutoGenerated: record.isAutoGenerated ?? false,
          preparedBy: record.preparedBy ?? "",
          reviewedBy: record.reviewedBy ?? "",
          approvedBy: record.approvedBy ?? "",
          notes: record.notes ?? "",
        }}
        isEdit
        apiPath={`/api/v1/general-ledger-financial-reporting/journal-entries/${id}`}
        returnPath={`/general-ledger-financial-reporting/journal-entries/${id}`}
      />
    </div>
  );
}
