import Link from "next/link";
import { ArrowLeft, Pencil } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { getSession } from "@/lib/auth/session";
import { hasPermission } from "@/lib/rbac";
import { getSpendAnalytic } from "@/lib/accounts-payable-vendor-management/service";
import { Badge } from "@/components/ui/badge";

export default async function SpendAnalyticDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!(await hasPermission(session.id, session.tenantId, "payable:read")))
    redirect("/accounts-payable-vendor-management");

  const { id } = await params;
  const record = await getSpendAnalytic(id, session.tenantId);
  if (!record) notFound();

  const canEdit = await hasPermission(
    session.id,
    session.tenantId,
    "payable:edit"
  );

  const fields: { label: string; value: React.ReactNode }[] = [
    { label: "Report Ref", value: record.reportRef },
    { label: "Report Type", value: record.reportType },
    { label: "Report Period", value: record.reportPeriod },
    { label: "Report Year", value: record.reportYear },
    { label: "Report Month", value: record.reportMonth },
    { label: "Currency", value: record.currency },
    {
      label: "Total Spend",
      value:
        record.totalSpend != null
          ? Number(record.totalSpend).toLocaleString()
          : null,
    },
    { label: "Total Orders", value: record.totalOrders },
    { label: "Total Invoices", value: record.totalInvoices },
    { label: "Total Payments", value: record.totalPayments },
    { label: "Average Payment Days", value: record.averagePaymentDays },
    {
      label: "On-Time Payment %",
      value:
        record.onTimePaymentPercent != null
          ? `${record.onTimePaymentPercent}%`
          : null,
    },
    {
      label: "Savings Identified",
      value:
        record.savingsIdentified != null
          ? Number(record.savingsIdentified).toLocaleString()
          : null,
    },
    {
      label: "Contract Compliance",
      value:
        record.contractCompliance != null
          ? `${record.contractCompliance}%`
          : null,
    },
    { label: "AI Model Version", value: record.aiModelVersion },
    { label: "Generated By", value: record.generatedByName },
    {
      label: "Status",
      value: (
        <Badge
          variant={
            record.status === "published"
              ? "success"
              : "secondary"
          }
        >
          {record.status}
        </Badge>
      ),
    },
    { label: "Notes", value: record.notes },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Link
            href="/accounts-payable-vendor-management/spend-analytics"
            className="rounded-md border border-gray-300 p-2 text-gray-500 hover:bg-gray-50"
          >
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              {record.reportRef}
            </h1>
            <p className="text-sm text-gray-500">Spend Analytics Details</p>
          </div>
        </div>
        {canEdit && (
          <Link
            href={`/accounts-payable-vendor-management/spend-analytics/${record.id}/edit`}
            className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            <Pencil className="h-4 w-4" /> Edit
          </Link>
        )}
      </div>

      <div className="rounded-lg border bg-white">
        <dl className="divide-y">
          {fields.map((f) => (
            <div
              key={f.label}
              className="grid grid-cols-3 gap-4 px-6 py-4 sm:grid-cols-4"
            >
              <dt className="text-sm font-medium text-gray-500">{f.label}</dt>
              <dd className="col-span-2 text-sm text-gray-900 sm:col-span-3">
                {f.value ?? <span className="text-gray-400">--</span>}
              </dd>
            </div>
          ))}
        </dl>
      </div>
    </div>
  );
}
