import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getSession } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import { hasPermission } from "@/lib/rbac";
import { GlfrForm } from "@/components/general-ledger-financial-reporting/glfr-form";
import type { FieldConfig } from "@/components/general-ledger-financial-reporting/glfr-form";

const FIELDS: FieldConfig[] = [
  {
    name: "statementType",
    label: "Statement Type",
    type: "select",
    required: true,
    options: [
      { value: "balance_sheet", label: "Balance Sheet" },
      { value: "income_statement", label: "Income Statement" },
      { value: "cash_flow", label: "Cash Flow" },
      { value: "equity_changes", label: "Equity Changes" },
      { value: "comprehensive_income", label: "Comprehensive Income" },
    ],
  },
  {
    name: "reportingStandard",
    label: "Reporting Standard",
    type: "select",
    options: [
      { value: "ifrs", label: "IFRS" },
      { value: "gaap", label: "GAAP" },
      { value: "local", label: "Local" },
    ],
  },
  { name: "periodStart", label: "Period Start", type: "datetime-local" },
  { name: "periodEnd", label: "Period End", type: "datetime-local" },
  { name: "fiscalYear", label: "Fiscal Year", type: "number" },
  {
    name: "currency",
    label: "Currency",
    type: "text",
    placeholder: "USD",
  },
  { name: "entityId", label: "Entity ID", type: "text" },
  { name: "totalAssets", label: "Total Assets", type: "text" },
  { name: "totalLiabilities", label: "Total Liabilities", type: "text" },
  { name: "totalEquity", label: "Total Equity", type: "text" },
  { name: "netIncome", label: "Net Income", type: "text" },
  { name: "generatedBy", label: "Generated By", type: "text" },
  { name: "approvedBy", label: "Approved By", type: "text" },
  { name: "notes", label: "Notes", type: "textarea" },
];

export default async function NewFinancialStatementPage(): Promise<React.ReactNode> {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!(await hasPermission(session.id, session.tenantId, "gl:create")))
    redirect("/general-ledger-financial-reporting/financial-statements");

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link
          href="/general-ledger-financial-reporting/financial-statements"
          className="rounded-md p-1 hover:bg-gray-100"
        >
          <ArrowLeft className="h-5 w-5 text-gray-500" />
        </Link>
        <h1 className="text-2xl font-bold text-gray-900">
          New Financial Statement
        </h1>
      </div>

      <div className="rounded-lg border bg-white p-6">
        <GlfrForm
          entityType="Financial Statement"
          apiPath="/api/v1/general-ledger-financial-reporting/financial-statements"
          fields={FIELDS}
          returnPath="/general-ledger-financial-reporting/financial-statements"
        />
      </div>
    </div>
  );
}
