import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getSession } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import { hasPermission } from "@/lib/rbac";
import { PscForm } from "@/components/procurement-supply-chain/psc-form";
import type { FieldConfig } from "@/components/procurement-supply-chain/psc-form";

const ANALYTICS_FIELDS: FieldConfig[] = [
  {
    name: "analyticsType",
    label: "Analytics Type",
    type: "select",
    required: true,
    options: [
      { value: "category_analysis", label: "Category Analysis" },
      { value: "vendor_analysis", label: "Vendor Analysis" },
      { value: "trend_analysis", label: "Trend Analysis" },
      { value: "savings_opportunity", label: "Savings Opportunity" },
      { value: "anomaly_detection", label: "Anomaly Detection" },
      { value: "forecast", label: "Forecast" },
    ],
  },
  { name: "title", label: "Title", type: "text", required: true },
  { name: "analysisPeriodStart", label: "Analysis Period Start", type: "datetime-local" },
  { name: "analysisPeriodEnd", label: "Analysis Period End", type: "datetime-local" },
  { name: "totalSpend", label: "Total Spend", type: "text" },
  { name: "currency", label: "Currency", type: "text", placeholder: "QAR" },
  { name: "savingsIdentified", label: "Savings Identified", type: "text" },
  { name: "savingsRealized", label: "Savings Realized", type: "text" },
  { name: "forecastNextPeriod", label: "Forecast Next Period", type: "text" },
  { name: "confidenceScore", label: "Confidence Score", type: "text" },
  { name: "aiModelUsed", label: "AI Model Used", type: "text" },
  { name: "dataPoints", label: "Data Points", type: "number" },
  { name: "generatedBy", label: "Generated By", type: "text" },
  { name: "notes", label: "Notes", type: "textarea" },
];

export default async function NewSpendAnalyticPage(): Promise<React.ReactNode> {
  const session = await getSession();
  if (!session) redirect("/login");
  if (
    !(await hasPermission(session.id, session.tenantId, "procurement:create"))
  )
    redirect("/procurement-supply-chain/spend-analytics");

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link
          href="/procurement-supply-chain/spend-analytics"
          className="rounded-md p-1 hover:bg-gray-100"
        >
          <ArrowLeft className="h-5 w-5 text-gray-500" />
        </Link>
        <h1 className="text-2xl font-bold text-gray-900">
          New Spend Analytic
        </h1>
      </div>

      <div className="rounded-lg border bg-white p-6">
        <PscForm
          entityType="Spend Analytic"
          apiPath="/api/v1/procurement-supply-chain/spend-analytics"
          fields={ANALYTICS_FIELDS}
          returnPath="/procurement-supply-chain/spend-analytics"
        />
      </div>
    </div>
  );
}
