import Link from "next/link";
import { Pencil, ArrowLeft } from "lucide-react";
import { getSession } from "@/lib/auth/session";
import { redirect, notFound } from "next/navigation";
import { hasPermission } from "@/lib/rbac";
import { getConsolidatedReport } from "@/lib/port-disbursement-accounting/service";
import { Badge } from "@/components/ui/badge";

export default async function ConsolidatedReportDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (
    !(await hasPermission(
      session.id,
      session.tenantId,
      "disbursement:read"
    ))
  )
    redirect("/port-disbursement-accounting");

  const { id } = await params;
  const record = await getConsolidatedReport(id, session.tenantId);
  if (!record) notFound();

  const canEdit = await hasPermission(
    session.id,
    session.tenantId,
    "disbursement:edit"
  );

  const details = [
    { label: "Report Ref", value: record.reportRef },
    { label: "Report Type", value: record.reportType },
    { label: "Report Period", value: record.reportPeriod },
    { label: "Report Year", value: record.reportYear?.toString() },
    { label: "Report Month", value: record.reportMonth?.toString() },
    { label: "Currency", value: record.currency },
    { label: "Total Ports", value: record.totalPorts?.toString() },
    { label: "Total Voyages", value: record.totalVoyages?.toString() },
    { label: "Total Proformas", value: record.totalProformas?.toString() },
    { label: "Total Finals", value: record.totalFinals?.toString() },
    {
      label: "Total Estimated Cost",
      value: record.totalEstimatedCost?.toLocaleString(),
    },
    {
      label: "Total Actual Cost",
      value: record.totalActualCost?.toLocaleString(),
    },
    {
      label: "Total Variance",
      value: record.totalVariance?.toLocaleString(),
    },
    {
      label: "Average Variance Percent",
      value: record.averageVariancePercent?.toLocaleString(),
    },
    { label: "AI Model Version", value: record.aiModelVersion },
    { label: "Generated By", value: record.generatedByName },
    { label: "Notes", value: record.notes },
    {
      label: "Created At",
      value: record.createdAt
        ? new Date(record.createdAt).toLocaleString()
        : "--",
    },
    {
      label: "Updated At",
      value: record.updatedAt
        ? new Date(record.updatedAt).toLocaleString()
        : "--",
    },
  ];

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link
          href="/port-disbursement-accounting/consolidated-reports"
          className="rounded-md p-1 hover:bg-gray-100"
        >
          <ArrowLeft className="h-5 w-5 text-gray-500" />
        </Link>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-gray-900">
            {record.reportRef}
          </h1>
          <p className="text-sm text-gray-500">
            {record.reportType} &mdash; {record.reportPeriod}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge
            variant={
              record.status === "published" ? "success" : "secondary"
            }
          >
            {record.status}
          </Badge>
          {canEdit && (
            <Link
              href={`/port-disbursement-accounting/consolidated-reports/${id}/edit`}
              className="inline-flex items-center gap-1.5 rounded-md border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
            >
              <Pencil className="h-3.5 w-3.5" /> Edit
            </Link>
          )}
        </div>
      </div>

      <div className="rounded-lg border bg-white p-6">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {details.map((d) => (
            <div key={d.label}>
              <p className="text-xs font-medium text-gray-500">{d.label}</p>
              <p className="mt-0.5 text-sm text-gray-900">
                {d.value ?? "--"}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
