import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getSession } from "@/lib/auth/session";
import { redirect, notFound } from "next/navigation";
import { hasPermission } from "@/lib/rbac";
import { getFinancialStatement } from "@/lib/general-ledger-financial-reporting/service";
import { GlfrForm } from "@/components/general-ledger-financial-reporting/glfr-form";
import type { FieldConfig } from "@/components/general-ledger-financial-reporting/glfr-form";

const FIELDS: FieldConfig[] = [
  {
    name: "statementType",
    label: "Statement Type",
    type: "select",
    required: true,
    options: [
      { value: "balance_sheet", label: "Balance Sheet" },
      { value: "income_statement", label: "Income Statement" },
      { value: "cash_flow", label: "Cash Flow" },
      { value: "equity_changes", label: "Equity Changes" },
      { value: "comprehensive_income", label: "Comprehensive Income" },
    ],
  },
  {
    name: "reportingStandard",
    label: "Reporting Standard",
    type: "select",
    options: [
      { value: "ifrs", label: "IFRS" },
      { value: "gaap", label: "GAAP" },
      { value: "local", label: "Local" },
    ],
  },
  { name: "periodStart", label: "Period Start", type: "datetime-local" },
  { name: "periodEnd", label: "Period End", type: "datetime-local" },
  { name: "fiscalYear", label: "Fiscal Year", type: "number" },
  {
    name: "currency",
    label: "Currency",
    type: "text",
    placeholder: "USD",
  },
  { name: "entityId", label: "Entity ID", type: "text" },
  { name: "totalAssets", label: "Total Assets", type: "text" },
  { name: "totalLiabilities", label: "Total Liabilities", type: "text" },
  { name: "totalEquity", label: "Total Equity", type: "text" },
  { name: "netIncome", label: "Net Income", type: "text" },
  { name: "generatedBy", label: "Generated By", type: "text" },
  { name: "approvedBy", label: "Approved By", type: "text" },
  { name: "notes", label: "Notes", type: "textarea" },
];

export default async function EditFinancialStatementPage({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<React.ReactNode> {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!(await hasPermission(session.id, session.tenantId, "gl:edit")))
    redirect("/general-ledger-financial-reporting/financial-statements");

  const { id } = await params;
  const record = await getFinancialStatement(id, session.tenantId);
  if (!record) notFound();

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link
          href={`/general-ledger-financial-reporting/financial-statements/${id}`}
          className="rounded-md p-1 hover:bg-gray-100"
        >
          <ArrowLeft className="h-5 w-5 text-gray-500" />
        </Link>
        <h1 className="text-2xl font-bold text-gray-900">
          Edit Financial Statement
        </h1>
      </div>

      <div className="rounded-lg border bg-white p-6">
        <GlfrForm
          entityType="Financial Statement"
          apiPath={`/api/v1/general-ledger-financial-reporting/financial-statements/${id}`}
          fields={FIELDS}
          initialData={{
            statementType: record.statementType,
            reportingStandard: record.reportingStandard ?? "",
            periodStart: record.periodStart
              ? new Date(record.periodStart).toISOString()
              : "",
            periodEnd: record.periodEnd
              ? new Date(record.periodEnd).toISOString()
              : "",
            fiscalYear: record.fiscalYear ?? "",
            currency: record.currency ?? "",
            entityId: record.entityId ?? "",
            totalAssets: record.totalAssets ?? "",
            totalLiabilities: record.totalLiabilities ?? "",
            totalEquity: record.totalEquity ?? "",
            netIncome: record.netIncome ?? "",
            generatedBy: record.generatedBy ?? "",
            approvedBy: record.approvedBy ?? "",
            notes: record.notes ?? "",
          }}
          isEdit
          returnPath={`/general-ledger-financial-reporting/financial-statements/${id}`}
        />
      </div>
    </div>
  );
}
