import { z } from "zod/v4";
import { metadataSchema } from "@/lib/validation";

// ==========================================
// Chart of Accounts
// ==========================================
export const createChartOfAccountSchema = z.object({
  accountType: z.enum(["asset", "liability", "equity", "revenue", "expense"]),
  accountCode: z.string().min(1).max(50),
  accountName: z.string().min(1).max(255),
  parentAccountId: z.string().max(100).optional(),
  accountLevel: z.number().int().optional(),
  currency: z.string().max(3).optional(),
  normalBalance: z.enum(["debit", "credit"]).optional(),
  isControlAccount: z.boolean().optional(),
  isReconcilable: z.boolean().optional(),
  isBankAccount: z.boolean().optional(),
  segment: z.string().max(100).optional(),
  costCenter: z.string().max(100).optional(),
  department: z.string().max(255).optional(),
  taxCode: z.string().max(50).optional(),
  openingBalance: z.string().optional(),
  currentBalance: z.string().optional(),
  description: z.string().optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updateChartOfAccountSchema = createChartOfAccountSchema.partial();

// ==========================================
// Journal Entries
// ==========================================
export const createJournalEntrySchema = z.object({
  entryType: z.enum(["standard", "adjusting", "closing", "reversing", "recurring", "accrual"]),
  entryDate: z.coerce.date().optional(),
  postingDate: z.coerce.date().optional(),
  periodId: z.string().max(100).optional(),
  description: z.string().optional(),
  currency: z.string().max(3).optional(),
  totalDebit: z.string().optional(),
  totalCredit: z.string().optional(),
  sourceModule: z.string().max(100).optional(),
  sourceDocumentRef: z.string().max(100).optional(),
  reversalEntryId: z.string().max(100).optional(),
  isAutoGenerated: z.boolean().optional(),
  preparedBy: z.string().max(255).optional(),
  reviewedBy: z.string().max(255).optional(),
  approvedBy: z.string().max(255).optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updateJournalEntrySchema = createJournalEntrySchema.partial();

// ==========================================
// Period Closures
// ==========================================
export const createPeriodClosureSchema = z.object({
  closureType: z.enum(["monthly", "quarterly", "annual", "interim", "soft_close"]),
  periodName: z.string().max(100).optional(),
  periodStart: z.coerce.date().optional(),
  periodEnd: z.coerce.date().optional(),
  fiscalYear: z.number().int().optional(),
  fiscalMonth: z.number().int().optional(),
  completedSteps: z.number().int().optional(),
  totalSteps: z.number().int().optional(),
  closedBy: z.string().max(255).optional(),
  closedAt: z.coerce.date().optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updatePeriodClosureSchema = createPeriodClosureSchema.partial();

// ==========================================
// Financial Statements
// ==========================================
export const createFinancialStatementSchema = z.object({
  statementType: z.enum(["balance_sheet", "income_statement", "cash_flow", "equity_changes", "comprehensive_income"]),
  reportingStandard: z.enum(["ifrs", "gaap", "local"]).optional(),
  periodStart: z.coerce.date().optional(),
  periodEnd: z.coerce.date().optional(),
  fiscalYear: z.number().int().optional(),
  currency: z.string().max(3).optional(),
  entityId: z.string().max(100).optional(),
  totalAssets: z.string().optional(),
  totalLiabilities: z.string().optional(),
  totalEquity: z.string().optional(),
  netIncome: z.string().optional(),
  generatedBy: z.string().max(255).optional(),
  approvedBy: z.string().max(255).optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updateFinancialStatementSchema = createFinancialStatementSchema.partial();

// ==========================================
// Segment Reports
// ==========================================
export const createSegmentReportSchema = z.object({
  reportType: z.enum(["entity", "trade_lane", "geography", "business_unit", "product_line"]),
  segmentName: z.string().max(255).optional(),
  periodStart: z.coerce.date().optional(),
  periodEnd: z.coerce.date().optional(),
  fiscalYear: z.number().int().optional(),
  currency: z.string().max(3).optional(),
  revenue: z.string().optional(),
  costOfRevenue: z.string().optional(),
  grossProfit: z.string().optional(),
  operatingExpenses: z.string().optional(),
  operatingIncome: z.string().optional(),
  segmentAssets: z.string().optional(),
  segmentLiabilities: z.string().optional(),
  interSegmentRevenue: z.string().optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updateSegmentReportSchema = createSegmentReportSchema.partial();

// ==========================================
// Consolidated Statements
// ==========================================
export const createConsolidatedStatementSchema = z.object({
  consolidationType: z.enum(["full", "proportional", "equity_method", "elimination"]),
  periodStart: z.coerce.date().optional(),
  periodEnd: z.coerce.date().optional(),
  fiscalYear: z.number().int().optional(),
  currency: z.string().max(3).optional(),
  parentEntity: z.string().max(255).optional(),
  minorityInterest: z.string().optional(),
  consolidatedRevenue: z.string().optional(),
  consolidatedNetIncome: z.string().optional(),
  consolidatedAssets: z.string().optional(),
  consolidatedLiabilities: z.string().optional(),
  consolidatedEquity: z.string().optional(),
  preparedBy: z.string().max(255).optional(),
  approvedBy: z.string().max(255).optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updateConsolidatedStatementSchema = createConsolidatedStatementSchema.partial();

// ==========================================
// Budgets
// ==========================================
export const createBudgetSchema = z.object({
  budgetType: z.enum(["annual", "quarterly", "rolling", "zero_based", "incremental"]),
  budgetName: z.string().max(255).optional(),
  fiscalYear: z.number().int().optional(),
  periodStart: z.coerce.date().optional(),
  periodEnd: z.coerce.date().optional(),
  currency: z.string().max(3).optional(),
  department: z.string().max(255).optional(),
  costCenter: z.string().max(100).optional(),
  totalBudgeted: z.string().optional(),
  totalActual: z.string().optional(),
  totalVariance: z.string().optional(),
  variancePercentage: z.string().optional(),
  currentRevision: z.number().int().optional(),
  preparedBy: z.string().max(255).optional(),
  approvedBy: z.string().max(255).optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updateBudgetSchema = createBudgetSchema.partial();

// ==========================================
// Variance Analyses
// ==========================================
export const createVarianceAnalysisSchema = z.object({
  analysisType: z.enum(["budget_vs_actual", "period_over_period", "forecast_vs_actual", "plan_vs_actual"]),
  periodStart: z.coerce.date().optional(),
  periodEnd: z.coerce.date().optional(),
  fiscalYear: z.number().int().optional(),
  currency: z.string().max(3).optional(),
  budgetAmount: z.string().optional(),
  actualAmount: z.string().optional(),
  varianceAmount: z.string().optional(),
  variancePercentage: z.string().optional(),
  favorableUnfavorable: z.enum(["favorable", "unfavorable"]).optional(),
  department: z.string().max(255).optional(),
  costCenter: z.string().max(100).optional(),
  accountCode: z.string().max(50).optional(),
  commentary: z.string().optional(),
  preparedBy: z.string().max(255).optional(),
  reviewedBy: z.string().max(255).optional(),
  notes: z.string().optional(),
  metadata: metadataSchema,
});
export const updateVarianceAnalysisSchema = createVarianceAnalysisSchema.partial();
