import { getSession } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import { hasPermission } from "@/lib/rbac";
import {
  GlfrForm,
  type FieldConfig,
} from "@/components/general-ledger-financial-reporting/glfr-form";
import { getCurrencyOptions } from "@/lib/lookups";

export default async function NewJournalEntryPage(): Promise<React.ReactNode> {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!(await hasPermission(session.id, session.tenantId, "gl:create")))
    redirect("/general-ledger-financial-reporting/journal-entries");

  const currencyOpts = await getCurrencyOptions();

  const JOURNAL_ENTRY_FIELDS: FieldConfig[] = [
    {
      name: "entryType",
      label: "Entry Type",
      type: "select",
      required: true,
      options: [
        { value: "standard", label: "Standard" },
        { value: "adjusting", label: "Adjusting" },
        { value: "closing", label: "Closing" },
        { value: "reversing", label: "Reversing" },
        { value: "recurring", label: "Recurring" },
        { value: "accrual", label: "Accrual" },
      ],
    },
    { name: "entryDate", label: "Entry Date", type: "datetime-local" },
    { name: "postingDate", label: "Posting Date", type: "datetime-local" },
    { name: "periodId", label: "Period ID", type: "text" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "currency", label: "Currency", type: "select", options: currencyOpts },
    { name: "totalDebit", label: "Total Debit", type: "text" },
    { name: "totalCredit", label: "Total Credit", type: "text" },
    { name: "sourceModule", label: "Source Module", type: "text" },
    { name: "sourceDocumentRef", label: "Source Document Ref", type: "text" },
    { name: "reversalEntryId", label: "Reversal Entry ID", type: "text" },
    { name: "isAutoGenerated", label: "Is Auto Generated", type: "checkbox" },
    { name: "preparedBy", label: "Prepared By", type: "text" },
    { name: "reviewedBy", label: "Reviewed By", type: "text" },
    { name: "approvedBy", label: "Approved By", type: "text" },
    { name: "notes", label: "Notes", type: "textarea" },
  ];
  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">
          New Journal Entry
        </h1>
        <p className="text-sm text-gray-500">
          Create a new GL journal entry
        </p>
      </div>
      <GlfrForm
        entityType="Journal Entry"
        fields={JOURNAL_ENTRY_FIELDS}
        apiPath="/api/v1/general-ledger-financial-reporting/journal-entries"
        returnPath="/general-ledger-financial-reporting/journal-entries"
      />
    </div>
  );
}
