import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getSession } from "@/lib/auth/session";
import { redirect, notFound } from "next/navigation";
import { hasPermission } from "@/lib/rbac";
import { db } from "@/lib/db";
import { eq, and, isNull } from "drizzle-orm";
import { isfComplianceReports } from "@/db/schema";
import { Badge } from "@/components/ui/badge";

function statusVariant(status: string) {
  switch (status) {
    case "published":
      return "success" as const;
    case "review":
      return "warning" as const;
    case "in_progress":
      return "default" as const;
    case "draft":
      return "secondary" as const;
    case "archived":
      return "secondary" as const;
    default:
      return "secondary" as const;
  }
}

function fmtDate(d: Date | string | null): string {
  if (!d) return "-";
  return new Date(d).toLocaleDateString();
}

function fmtDateTime(d: Date | string | null): string {
  if (!d) return "-";
  return new Date(d).toLocaleString();
}

function formatJson(value: unknown): string {
  if (value == null) return "-";
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

export default async function ComplianceReportDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await getSession();
  if (!session) redirect("/login");
  if (!(await hasPermission(session.id, session.tenantId, "infra:read")))
    redirect("/infrastructure-security");

  const { id } = await params;

  const record = await db
    .select()
    .from(isfComplianceReports)
    .where(
      and(
        eq(isfComplianceReports.id, id),
        eq(isfComplianceReports.tenantId, session.tenantId),
        isNull(isfComplianceReports.deletedAt)
      )
    )
    .limit(1)
    .then((r) => r[0]);

  if (!record) notFound();

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link
          href="/infrastructure-security/compliance-reports"
          className="rounded-md p-1 hover:bg-gray-100"
        >
          <ArrowLeft className="h-5 w-5 text-gray-500" />
        </Link>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-gray-900">
            {record.reportName}
          </h1>
          <p className="text-sm text-gray-500">
            {record.reportCode} &middot;{" "}
            {record.reportType.replace(/_/g, " ").toUpperCase()}
          </p>
        </div>
      </div>

      <div className="rounded-lg border bg-white p-6">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <div>
            <p className="text-xs font-medium text-gray-500">Report Name</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {record.reportName}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Report Code</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {record.reportCode}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Report Type</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {record.reportType.replace(/_/g, " ").toUpperCase()}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Framework</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {record.framework ?? "-"}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Status</p>
            <div className="mt-0.5">
              <Badge variant={statusVariant(record.status)}>
                {record.status.replace(/_/g, " ")}
              </Badge>
            </div>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Overall Score</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {record.overallScore != null ? `${record.overallScore}%` : "-"}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Period Start</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {fmtDate(record.periodStart)}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Period End</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {fmtDate(record.periodEnd)}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Generated By</p>
            <p className="mt-0.5 font-mono text-xs text-gray-900">
              {record.generatedBy ?? "-"}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Reviewed By</p>
            <p className="mt-0.5 font-mono text-xs text-gray-900">
              {record.reviewedBy ?? "-"}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Reviewed At</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {fmtDateTime(record.reviewedAt)}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Published At</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {fmtDateTime(record.publishedAt)}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Created At</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {fmtDateTime(record.createdAt)}
            </p>
          </div>
          <div>
            <p className="text-xs font-medium text-gray-500">Updated At</p>
            <p className="mt-0.5 text-sm text-gray-900">
              {fmtDateTime(record.updatedAt)}
            </p>
          </div>
        </div>

        {record.notes && (
          <div className="mt-6 border-t pt-4">
            <p className="text-xs font-medium text-gray-500">Notes</p>
            <p className="mt-1 whitespace-pre-wrap text-sm text-gray-700">
              {record.notes}
            </p>
          </div>
        )}

        {record.findings != null && (
          <div className="mt-6 border-t pt-4">
            <p className="text-xs font-medium text-gray-500">Findings</p>
            <pre className="mt-1 overflow-x-auto rounded bg-gray-50 p-3 text-xs text-gray-700">
              {formatJson(record.findings)}
            </pre>
          </div>
        )}

        {record.recommendations != null && (
          <div className="mt-6 border-t pt-4">
            <p className="text-xs font-medium text-gray-500">
              Recommendations
            </p>
            <pre className="mt-1 overflow-x-auto rounded bg-gray-50 p-3 text-xs text-gray-700">
              {formatJson(record.recommendations)}
            </pre>
          </div>
        )}

        {record.evidenceRefs != null && (
          <div className="mt-6 border-t pt-4">
            <p className="text-xs font-medium text-gray-500">
              Evidence References
            </p>
            <pre className="mt-1 overflow-x-auto rounded bg-gray-50 p-3 text-xs text-gray-700">
              {formatJson(record.evidenceRefs)}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}
